config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :rails_tips
  
	root "posts#index"
	
	#Basic Authentication (Login)
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
	
	get "login", to:"sessions#new"
	post "login", to:"sessions#create"
	post "logout", to:"sessions#destroy"
	#************************************************
	
	resources :posts
	resources :ruby_tips
  
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	include PgSearch::Model
	
	has_prefix_id :article
	
	pg_search_scope :search, against: [:title, :content], using: { tsearch: { 
																																			prefix: true,
																																			dictionary: "english",
																																			any_word: true		
																																		} 
																																	}
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/post.rb
class Post < ApplicationRecord
	#10-27-22
	include PgSearch::Model
	
	pg_search_scope :search, against: [:title, :content], using: { tsearch: { 
																																			prefix: true,
																																			dictionary: "english",
																																			any_word: true
																																			
																															} }
	#10-25-22
	#This makes the URL IDs unguessable (unless your code and the salt is visible on Github)
	has_prefix_id :post#, salt: "yoursalt" - this is optional, a global 														salt is set in an intializer
	
	
end

app/models/rails_tip.rb
class RailsTip < ApplicationRecord
	has_prefix_id :rails_tip
end

app/models/ruby_tip.rb
class RubyTip < ApplicationRecord
	has_prefix_id :ruby_tip
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_current_user
	
	
	def set_current_user
		if session[:user_id]
 			Current.user = User.find_by(id: session[:user_id])
		else
			#redirect_to root_path
 		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles
  def index
    @articles = Article.all
		@articles = Article.search(params[:query]) if params[:query].present?
  end

  # GET /articles/1
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: "Article was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /articles/1
  def update
    if @article.update(article_params)
      redirect_to @article, notice: "Article was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /articles/1
  def destroy
    @article.destroy
    redirect_to articles_url, notice: "Article was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts
  def index
    @posts = Post.all.order(created_at: :desc)
		@posts = Post.search(params[:query]) if params[:query].present?
	end
 

  # GET /posts/1
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/rails_tips_controller.rb
class RailsTipsController < ApplicationController
  before_action :set_rails_tip, only: %i[ show edit update destroy ]

  # GET /rails_tips
  def index
    @rails_tips = RailsTip.all
  end

  # GET /rails_tips/1
  def show
  end

  # GET /rails_tips/new
  def new
    @rails_tip = RailsTip.new
  end

  # GET /rails_tips/1/edit
  def edit
  end

  # POST /rails_tips
  def create
    @rails_tip = RailsTip.new(rails_tip_params)

    if @rails_tip.save
      redirect_to @rails_tip, notice: "Rails tip was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /rails_tips/1
  def update
    if @rails_tip.update(rails_tip_params)
      redirect_to @rails_tip, notice: "Rails tip was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /rails_tips/1
  def destroy
    @rails_tip.destroy
    redirect_to rails_tips_url, notice: "Rails tip was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rails_tip
      @rails_tip = RailsTip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rails_tip_params
      params.require(:rails_tip).permit(:title, :content)
    end
end

app/controllers/ruby_tips_controller.rb
class RubyTipsController < ApplicationController
  before_action :set_ruby_tip, only: %i[ show edit update destroy ]

  # GET /ruby_tips
  def index
    @ruby_tips = RubyTip.all
  end

  # GET /ruby_tips/1
  def show
  end

  # GET /ruby_tips/new
  def new
    @ruby_tip = RubyTip.new
  end

  # GET /ruby_tips/1/edit
  def edit
  end

  # POST /ruby_tips
  def create
    @ruby_tip = RubyTip.new(ruby_tip_params)

    if @ruby_tip.save
      redirect_to @ruby_tip, notice: "Ruby tip was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /ruby_tips/1
  def update
    if @ruby_tip.update(ruby_tip_params)
      redirect_to @ruby_tip, notice: "Ruby tip was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /ruby_tips/1
  def destroy
    @ruby_tip.destroy
    redirect_to ruby_tips_url, notice: "Ruby tip was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ruby_tip
      @ruby_tip = RubyTip.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ruby_tip_params
      params.require(:ruby_tip).permit(:title, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	
  def new
  end

  def create
		user = User.find_by(email: params[:email])
		if user.present? && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path , notice: "Successfully logged in."
		else
			flash[:alert] = "Invalid email or password"
			render :new
		end
  end

  def destroy
		session[:user_id] = nil
		redirect_to root_path ,notice: "logged out"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rails_tips_helper.rb
module RailsTipsHelper
end

app/helpers/ruby_tips_helper.rb
module RubyTipsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <h2><%= link_to article.title, article_path(article) %></h2>
  </p>

  <p>
    <%= sanitize article.content %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, :size => 80 %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <details>
      <summary>If you need to add special markup...</summary>
    <%= form.text_area :content, id: :article_content, rows: 20, cols: 80 %>
    </details>
    <trix-editor input="article_content"></trix-editor>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles - Many of these are works in progress, updates coming...</h1>

      <div turbo_frame="search"><%= form_with url: "", method: :get, data: {turbo_frame: "articles", turbo_action: "advance", controller: "search", action: "input->search#submit"} do |form| %>
  
        <%= form.search_field :query, value: params[:query], placeholder: 'Search Articles...' %>
      <% end %>
    </div>
</div>
<% if Current.user %>
  <%= link_to "New article", new_article_path %>
<% end %>

<%= turbo_frame_tag "articles" do %>
<p id="articles">
  <%= render @articles %>
</p>
<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>
  </br></br></br></br></br>
  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kentastic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/trix@2.0.0-beta.0/dist/trix.css">
      <script type="text/javascript" src="https://unpkg.com/trix@2.0.0-beta.0/dist/trix.umd.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <a href="/"><h1>Becoming Kentastic</h1></a>
      <p>Come along for the ride with someone in their 50s learning how to code</p>
    </header>
    
    <nav>
      <a href="/posts">Posts</a>
      <a href="/ruby_tips">Ruby Tips</a>
      <a href="/rails_tips">Rails Tips</a>
      <a href="/articles">Articles</a>
    </nav>
    
    <%= yield %>
    
    <footer>
      <p> © Becoming Kentastic Sunday October 23, 2022 -  <%=Time.zone.now.to_fs(:long) %>
      </p>
    </footer>
      
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, :size => 80 %>
  </div>
  
  <div>
    <%= form.label :content, style: "display: block" %>
    <details>
      <summary>If you need to add special markup...</summary>
      <%= form.text_area :content, id: :post_content, rows: 20, cols: 80 %>
    </deatils>
   </div>
   
  <trix-editor input="post_content"></trix-editor>
      
 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <h2><%= link_to post.title, post_path(post) %></h2>
  </p>
  <p>
    <%= sanitize post.content %>
  </p>
  
  
  <p>
    First posted: <%= post.created_at.to_fs(:long_ordinal)%></br>
    Last updated: <%= post.updated_at.to_fs(:long_ordinal)%></p>
</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Kentastic Posts</h1>
<p>Come along for the ride, some of these are stream of consciousness</p>

      <div turbo_frame="search"><%= form_with url: "", method: :get, data: {turbo_frame: "posts", turbo_action: "advance", controller: "search", action: "input->search#submit"} do |form| %>
  
        <%= form.search_field :query, value: params[:query], placeholder: 'Search Posts...' %>
      <% end %>
    </div>

<% if Current.user %>
  <%= link_to "New post", new_post_path %>
<% end %>


<%= turbo_frame_tag "posts" do %>
<p id="posts">
  <%= render @posts %>
</p>
<% end %>

app/views/posts/new.html.erb
<h1>New post y'all'</h1>
<%= render "form", post: @post %>
<br>
<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Back to posts", posts_path %>
  
  <% if Current.user %>
  <%= link_to "Edit this post", edit_post_path(@post) %>
  </br></br></br></br></br>
  <%= button_to "Destroy this post", @post, method: :delete %>
  <% end %>
</div>

app/views/rails_tips/_form.html.erb
<%= form_with(model: rails_tip) do |form| %>
  <% if rails_tip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rails_tip.errors.count, "error") %> prohibited this rails_tip from being saved:</h2>

      <ul>
        <% rails_tip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rails_tips/_rails_tip.html.erb
<div id="<%= dom_id rails_tip %>">
  <p>
    <strong>Title:</strong>
    <%= rails_tip.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= rails_tip.content %>
  </p>

</div>

app/views/rails_tips/edit.html.erb
<h1>Editing rails tip</h1>

<%= render "form", rails_tip: @rails_tip %>

<br>

<div>
  <%= link_to "Show this rails tip", @rails_tip %> |
  <%= link_to "Back to rails tips", rails_tips_path %>
</div>

app/views/rails_tips/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rails tips</h1>

<div id="rails_tips">
  <% @rails_tips.each do |rails_tip| %>
    <%= render rails_tip %>
    <p>
      <%= link_to "Show this Rails tip", rails_tip %>
    </p>
  <% end %>
</div>

<% if Current.user %>
  <%= link_to "New Rails tip", new_rails_tip_path %>
<% end %>

app/views/rails_tips/new.html.erb
<h1>New rails tip</h1>

<%= render "form", rails_tip: @rails_tip %>

<br>

<div>
  <%= link_to "Back to rails tips", rails_tips_path %>
</div>

app/views/rails_tips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @rails_tip %>

<div>
  <%= link_to "Edit this rails tip", edit_rails_tip_path(@rails_tip) %> |
  <%= link_to "Back to rails tips", rails_tips_path %>

  <%= button_to "Destroy this rails tip", @rails_tip, method: :delete %>
</div>

app/views/ruby_tips/_form.html.erb
<%= form_with(model: ruby_tip) do |form| %>
  <% if ruby_tip.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ruby_tip.errors.count, "error") %> prohibited this ruby_tip from being saved:</h2>

      <ul>
        <% ruby_tip.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/ruby_tips/_ruby_tip.html.erb
<div id="<%= dom_id ruby_tip %>">
  <p>
    <strong>Title:</strong>
    <%= ruby_tip.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= ruby_tip.content %>
  </p>

</div>

app/views/ruby_tips/edit.html.erb
<h1>Editing ruby tip</h1>

<%= render "form", ruby_tip: @ruby_tip %>

<br>

<div>
  <%= link_to "Show this ruby tip", @ruby_tip %> |
  <%= link_to "Back to ruby tips", ruby_tips_path %>
</div>

app/views/ruby_tips/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ruby tips</h1>

<div id="ruby_tips">
  <% @ruby_tips.each do |ruby_tip| %>
    <%= render ruby_tip %>
    <p>
      <%= link_to "Show this Ruby tip", ruby_tip %>
    </p>
  <% end %>
</div>

<% if Current.user %>
  <%= link_to "New Ruby tip", new_ruby_tip_path %>
<% end %>

app/views/ruby_tips/new.html.erb
<h1>New ruby tip</h1>

<%= render "form", ruby_tip: @ruby_tip %>

<br>

<div>
  <%= link_to "Back to ruby tips", ruby_tips_path %>
</div>

app/views/ruby_tips/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ruby_tip %>

<div>
  <%= link_to "Edit this ruby tip", edit_ruby_tip_path(@ruby_tip) %> |
  <%= link_to "Back to ruby tips", ruby_tips_path %>

  <%= button_to "Destroy this ruby tip", @ruby_tip, method: :delete %>
</div>